<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTgP4Slc\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTgP4Slc/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTgP4Slc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTgP4Slc\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerTgP4Slc\srcApp_KernelProdContainer([
    'container.build_hash' => 'TgP4Slc',
    'container.build_id' => 'd0d9627b',
    'container.build_time' => 1601993012,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTgP4Slc');
