<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxIC4rO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxIC4rO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGxIC4rO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGxIC4rO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGxIC4rO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GxIC4rO',
    'container.build_id' => '18f2efc6',
    'container.build_time' => 1602054807,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxIC4rO');
